# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookStore_MojtabaMirzadeh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookStore_MojtabaMirzadeh


pod 'AlamofireObjectMapper', '~> 6.2'
pod 'NVActivityIndicatorView', '~> 4.4.1'
pod 'Kingfisher', '~> 4.10.1'
pod 'Toast-Swift', '~> 4.0.1'
pod 'RealmSwift'

end
